<testsuite name="features.login.Login using Google Account" tests="2" errors="2" failures="0" skipped="0" time="0.008603" timestamp="2024-01-05T20:31:43.233943" hostname="DESKTOP-FHLCL6Q"><testcase classname="features.login.Login using Google Account" name="Successfully logging in using GitTrackr Account" status="failed" time="0.005326"><error type="WebDriverException" message="Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home&#10;">
<![CDATA[
Failing step: Given I am on the GitTrackr homepage ... failed in 0.005s
Location: tests/acceptance/features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "tests\acceptance\steps\login.py", line 13, in step_impl
    context.browser = webdriver.Chrome()
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Successfully logging in using GitTrackr Account
    Given I am on the GitTrackr homepage ... failed in 0.005s
    When I click the Login button ... skipped in 0.000s
    Then I should be redirected to the login page ... skipped in 0.000s
    When I click sign in with google button ... skipped in 0.000s
    Then I should be redirected to google oauth choose account selection ... skipped in 0.000s
    When I fill the email address ... skipped in 0.000s
    And I fill the password ... skipped in 0.000s
    And I click next ... skipped in 0.000s
    Then I should be redirected to the GitTrackr dashboard ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="features.login.Login using Google Account" name="Failed login attempt using GitTrackr Account" status="failed" time="0.003277"><error type="WebDriverException" message="Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home&#10;">
<![CDATA[
Failing step: Given I am on the GitTrackr homepage ... failed in 0.003s
Location: tests/acceptance/features/login.feature:18
Traceback (most recent call last):
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "tests\acceptance\steps\login.py", line 13, in step_impl
    context.browser = webdriver.Chrome()
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Airlangga\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Failed login attempt using GitTrackr Account
    Given I am on the GitTrackr homepage ... failed in 0.003s
    When I click the Login button ... skipped in 0.000s
    Then I should be redirected to the login page ... skipped in 0.000s
    When I click sign in with google button ... skipped in 0.000s
    Then I should be redirected to google oauth choose account selection ... skipped in 0.000s
    When I fill the email address ... skipped in 0.000s
    And I fill the wrong password ... skipped in 0.000s
    And I click next ... skipped in 0.000s
    Then I should stay on the login page ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>